# This is a basic workflow to help you get started with Actions

name: Changelog

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the gh-pages branch
  #push:
    #branches: [ gh-pages ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  gitlog-and-write:
    runs-on: ubuntu-latest
    steps:
      - name : get commits
        uses : jcblw/bash@master
        with:
          args : "git log $(git describe --abbrev=0 --tags $(git rev-list --tags --skip=2 --max-count=5))..HEAD --pretty=format:'%cs: %s' --no-merges > ./changelog.md"
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Update changelog.md stats'
          default_author: github_actions
          branch: gh-pages
        
        
