name: Build and Deploy
on:
  push:
    branches:
      - theData
      
  workflow_dispatch:
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2.3.4
        with:
          ref: theData
          path: src
      - name: Checkout current
        uses: actions/checkout@v2.3.4
        with:
          ref: main
          path: live
      - name: Setup NodeJS
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '14'
      - name: Install npm and deps
        run: |
          npm install -g npm@7
          cd src
          npm install --no-audit
      - name: Build site
        run: |
          cd src
          npm run build
      - name: Prepare deployment
        run: |
          rm -rf live/*
          cp -r src/public/* live
      - name: Commit & deploy
        uses: EndBug/add-and-commit@v7.4.0
        with:
          cwd: "live"
          branch: main
          message: "deploy: ${{ github.sha }}"
          default_author: github_actions
