name: "Update data/*.json"
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  update-data:
    name: Run scripts/update_data.py
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        name: Checkout repo
        with:
          ref: theData
          token: ${{ secrets.REPO_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v2.3.0
        with:
          python-version: "3.7"
      - name: Run script
        run: |
          python3 scripts/update_data.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v7.3.0
        with:
          message: 'Update data/*.json stats'
          default_author: github_actions
          branch: theData
